version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 7
    target-branch: "master"
  - package-ecosystem: "npm"
    directory: "/server/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 7
    target-branch: "master"
