id: security-best-practices
name: Security & Code Quality
description: Security frameworks, accessibility guidelines, performance optimization, and code quality best practices for building secure, maintainable, and high-performance applications.
tags: [security, accessibility, performance, code-quality, owasp, a11y, optimization, best-practices]
items:
  # Security & Quality Instructions
  - path: instructions/security-and-owasp.instructions.md
    kind: instruction
  - path: instructions/performance-optimization.instructions.md
    kind: instruction
  - path: instructions/self-explanatory-code-commenting.instructions.md
    kind: instruction

  # Security & Safety Prompts
  - path: prompts/ai-prompt-engineering-safety-review.prompt.md
    kind: prompt

display:
  ordering: alpha
  show_badge: true
