version: "3.8"
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
      - redis
      - minio
    volumes:
      - ./apps/server:/usr/src/app:rw
      - /usr/src/app/node_modules

  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - server
    volumes:
      - ./apps/client:/usr/src/app:rw
      - /usr/src/app/node_modules

volumes:
  mongo-data:
  minio-data:
