name: Label Triggered Code Reviews

on:
  pull_request:
    types: [labeled, synchronize, opened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  check-labels:
    runs-on: ubuntu-latest
    outputs:
      copilot_review: ${{ steps.check.outputs.copilot_review }}
      github_actions_review: ${{ steps.check.outputs.github_actions_review }}
      coderabbitai_review: ${{ steps.check.outputs.coderabbitai_review }}
    steps:
      - name: Check for review labels
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);

            core.setOutput('copilot_review', labels.includes('copilot-review'));
            core.setOutput('github_actions_review', labels.includes('github-actions-review'));
            core.setOutput('coderabbitai_review', labels.includes('coderabbitai-review'));

            console.log('PR Labels:', labels);
            console.log('Copilot review requested:', labels.includes('copilot-review'));
            console.log('GitHub Actions review requested:', labels.includes('github-actions-review'));
            console.log('CodeRabbit AI review requested:', labels.includes('coderabbitai-review'));

  copilot-review:
    needs: check-labels
    if: needs.check-labels.outputs.copilot_review == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint for code analysis
        run: |
          echo " GitHub Copilot Review Triggered" >> copilot-review.md
          echo "## Code Analysis Results" >> copilot-review.md
          echo "" >> copilot-review.md

          # Run ESLint and capture output
          if yarn lint 2>&1 | tee eslint-output.txt; then
            echo " ESLint passed successfully" >> copilot-review.md
          else
            echo " ESLint found issues:" >> copilot-review.md
            echo "\`\`\`" >> copilot-review.md
            cat eslint-output.txt >> copilot-review.md
            echo "\`\`\`" >> copilot-review.md
          fi

          echo "" >> copilot-review.md
          echo "## Automated Suggestions" >> copilot-review.md
          echo "- Review TypeScript types and interfaces" >> copilot-review.md
          echo "- Check for proper error handling" >> copilot-review.md
          echo "- Validate React component patterns" >> copilot-review.md
          echo "- Ensure proper authentication flows" >> copilot-review.md

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const reviewContent = fs.readFileSync('copilot-review.md', 'utf8');

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: reviewContent
            });

      - name: Remove copilot-review label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'copilot-review'
            });

  github-actions-review:
    needs: check-labels
    if: needs.check-labels.outputs.github_actions_review == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run comprehensive checks
        run: |
          echo " GitHub Actions Review Triggered" > actions-review.md
          echo "## Build & Test Results" >> actions-review.md
          echo "" >> actions-review.md

      - name: Type checking
        run: |
          echo "### TypeScript Type Checking" >> actions-review.md
          if yarn tsc --noEmit 2>&1 | tee tsc-output.txt; then
            echo " TypeScript compilation successful" >> actions-review.md
          else
            echo "❌ TypeScript errors found:" >> actions-review.md
            echo "\`\`\`" >> actions-review.md
            cat tsc-output.txt >> actions-review.md
            echo "\`\`\`" >> actions-review.md
          fi
          echo "" >> actions-review.md

      - name: Build check
        run: |
          echo "### Build Verification" >> actions-review.md
          if yarn build 2>&1 | tee build-output.txt; then
            echo " Build completed successfully" >> actions-review.md
          else
            echo "❌ Build failed:" >> actions-review.md
            echo "\`\`\`" >> actions-review.md
            tail -50 build-output.txt >> actions-review.md
            echo "\`\`\`" >> actions-review.md
          fi
          echo "" >> actions-review.md

      - name: Security audit
        run: |
          echo "### Security Audit" >> actions-review.md
          if yarn audit --level moderate 2>&1 | tee audit-output.txt; then
            echo " No security vulnerabilities found" >> actions-review.md
          else
            echo " Security vulnerabilities detected:" >> actions-review.md
            echo "\`\`\`" >> actions-review.md
            cat audit-output.txt >> actions-review.md
            echo "\`\`\`" >> actions-review.md
          fi
          echo "" >> actions-review.md

      - name: Package analysis
        run: |
          echo "### Package Analysis" >> actions-review.md
          echo "#### Bundle Size Analysis" >> actions-review.md

          # Analyze package.json for potential improvements
          echo "- Checking for outdated dependencies..." >> actions-review.md
          echo "- Analyzing bundle size impact..." >> actions-review.md
          echo "- Reviewing dev vs production dependencies..." >> actions-review.md
          echo "" >> actions-review.md

          echo "#### Recommendations" >> actions-review.md
          echo "- Consider updating dependencies regularly" >> actions-review.md
          echo "- Review unused dependencies" >> actions-review.md
          echo "- Ensure proper tree-shaking" >> actions-review.md

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const reviewContent = fs.readFileSync('actions-review.md', 'utf8');

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: reviewContent
            });

      - name: Remove github-actions-review label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'github-actions-review'
            });

  coderabbitai-setup:
    needs: check-labels
    if: needs.check-labels.outputs.coderabbitai_review == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CodeRabbit AI Review
        uses: actions/github-script@v7
        with:
          script: |
            // CodeRabbit AI will automatically review when the label is present
            // This job just ensures the workflow runs and removes the label after triggering

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ` **CodeRabbit AI Review Triggered**

            CodeRabbit AI is now analyzing this pull request. The review will appear shortly with:
            - Line-by-line code analysis
            - Security vulnerability detection
            - Performance optimization suggestions
            - Best practice recommendations
            - Code quality improvements

            Please wait for the CodeRabbit AI bot to complete its analysis.`
            });

      - name: Remove coderabbitai-review label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'coderabbitai-review'
            });

  notify-completion:
    needs: [check-labels, copilot-review, github-actions-review, coderabbitai-setup]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Notify review completion
        uses: actions/github-script@v7
        with:
          script: |
            const { copilot, githubActions, coderabbit } = {
              copilot: '${{ needs.check-labels.outputs.copilot_review }}' === 'true',
              githubActions: '${{ needs.check-labels.outputs.github_actions_review }}' === 'true',
              coderabbit: '${{ needs.check-labels.outputs.coderabbitai_review }}' === 'true'
            };

            if (copilot || githubActions || coderabbit) {
              const triggeredReviews = [];
              if (copilot) triggeredReviews.push(' GitHub Copilot');
              if (githubActions) triggeredReviews.push(' GitHub Actions');
              if (coderabbit) triggeredReviews.push(' CodeRabbit AI');

              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `##  Automated Reviews Completed

            The following reviews have been triggered and completed:
            ${triggeredReviews.map(review => \`- ${review}\`).join('\\n')}

            All review labels have been automatically removed. You can re-apply them anytime to trigger additional reviews.`
              });
            }
