name: reviewdog
on:
  pull_request:
  workflow_run:
    workflows: ["Code Quality"]
    types:
      - completed
    branches:
      - main
jobs:
  biome:
    name: runner / Biome
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
